.github/workflows/android-publish.yml
.github/workflows/ios-build.yml
.github/workflows/ios-publish.yml

Just ensures that PRs will at least build before merging

Add build steps that run on non main branches

---

.github/workflows/ios-build.yml

Import ios code signing cert and ensure we sign develop builds

add build pr ci

---

.github/workflows/web-publish.yml
LiftLog.Web/Program.cs

This will publish the web project to the github pages site, allowing for a demo of the app without having to install it

Add a step to publish to github pages

---

LiftLog.CypressTests/cypress/e2e/completing-a-session.cy.js
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/Settings/ManageSessionPage.razor
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Shared/Presentation/AddExerciseCard.razor
LiftLog.Ui/Shared/Presentation/SessionComponent.razor
LiftLog.Ui/Shared/Presentation/WeightDisplay.razor

Add a freeform mode which starts an empty session

Add a freeform session mode

---

LiftLog.CypressTests/cypress/e2e/completing-a-session.cy.js
LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Lib/Models/SessionModels.cs
LiftLog.Tests/Sessions.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV1.cs
LiftLog.Ui/Pages/History/HistoryEditPage.razor
LiftLog.Ui/Pages/SessionPage.razor
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Services/SessionService.cs
LiftLog.Ui/Shared/Presentation/IconButton.razor
LiftLog.Ui/Shared/Presentation/SessionComponent.razor
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Store/CurrentSession/CurrentSessionActions.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs

- Update exercise models to include notes
- Add a dialog for updating the exercise notes
- Show the previous notes when holding down the previous button

Add Exercise notes

---

LiftLog.CypressTests/cypress/e2e/completing-a-session.cy.js
LiftLog.CypressTests/cypress/e2e/creating-a-plan.cy.js
LiftLog.Ui/Pages/Settings/ManageSessionPage.razor
LiftLog.Ui/Shared/Presentation/EditableIncrementer.razor
LiftLog.Ui/Shared/Presentation/ExerciseEditor.razor
LiftLog.Ui/Shared/Presentation/FixedIncrementer.razor
LiftLog.Ui/Shared/Presentation/Switch.razor
LiftLog.Ui/Store/SessionEditor/SessionEditorActions.cs
LiftLog.Ui/Store/SessionEditor/SessionEditorReducers.cs

The session editor had exercise editing inline and had a lot of very specific fluxor actions.  This refactor just pulls all that behaviour into a EditExercise component.
This will be useful if we want to allow for editing everything during the session

Refactor exercise editing into own component

---

LiftLog.App/Services/AppPurchaseService.cs
LiftLog.App/Services/AppThemeProvider.cs
LiftLog.App/Services/MauiNotificationService.cs
LiftLog.App/Services/MauiShareTextExporter.cs
LiftLog.App/Services/ThemeColorUpdateService.cs
LiftLog.Backend.Functions/GenerateAiWorkout.cs
LiftLog.Backend.Functions/Services/AppleAppStorePurchaseVerificationService.cs
LiftLog.Backend.Functions/Services/GooglePlayPurchaseVerificationService.cs
LiftLog.Backend.Functions/Services/GptAiWorkoutPlanner.cs
LiftLog.Backend.Functions/Services/PurchaseVerificationService.cs
LiftLog.Backend.Functions/Services/RateLimitService.cs
LiftLog.Backend.Functions/Services/WebAuthPurchaseVerificationService.cs
LiftLog.Lib/Serialization/ImmutableDictionaryJsonConverter.cs
LiftLog.Lib/Serialization/ImmutableListValueJsonConverter.cs
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Services/ApiBasedAiWorkoutPlanner.cs
LiftLog.Ui/Services/KeyValueCurrentProgramRepository.cs
LiftLog.Ui/Services/KeyValueProgressRepository.cs
LiftLog.Ui/Services/SessionService.cs
LiftLog.Ui/Store/AiSessionCreator/AiSessionCreatorEffects.cs
LiftLog.Ui/Store/App/AppEffects.cs
LiftLog.Ui/Store/App/AppStateInitMiddleware.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionEffects.cs
LiftLog.Ui/Store/Program/PersistProgramMiddleware.cs
LiftLog.Ui/Store/Program/ProgramEffects.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Web/Services/LocalStorageKeyValueStore.cs
LiftLog.Web/Services/WebAppPurchaseService.cs
LiftLog.Web/Services/WebNotificationService.cs
LiftLog.Web/Services/WebTextExporter.cs

Use C# 12 primary constructors on all classes

---

LiftLog.Ui/Pages/Feed/ViewFeedSessionPage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/Presentation/FeedItemCardContent.razor
LiftLog.Ui/Shared/Presentation/SessionComponent.razor
LiftLog.Ui/Store/Feed/FeedState.cs

Show who completed the session from the feed in the session snackbar

---

LiftLog.Api/Controllers/EventsController.cs
LiftLog.Api/Db/UserDataContext.cs
LiftLog.Api/Db/UserEventFilterExtensions.cs
LiftLog.Api/Models/UserEventFilter.cs
LiftLog.Api/Properties/launchSettings.json
LiftLog.Api/Validators/UserRequestValidators.cs
LiftLog.Lib/Models/UserActions.cs
LiftLog.Ui/Store/Feed/FeedEffects.FeedItems.cs

The api to get feed events since api didn't really make sense when subscribing to a new user.  This way, we can get all events for a user when we subscribe to their feed

Add ability to get events from the api for a user with different sinces

---

LiftLog.Ui/Models/SettingStorageDao/SettingsStorageDaoV2.cs
LiftLog.Ui/Models/SettingStorageDao/SettingsStorageDaoV2.proto
LiftLog.Ui/Store/Program/ProgramActions.cs
LiftLog.Ui/Store/Program/ProgramReducers.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs

When using export and import features, include the user's saved plans

Export saved plans

---

LiftLog.Cypress/cypress/e2e/completing-a-session.cy.js
LiftLog.Cypress/cypress/e2e/creating-a-plan.cy.js
LiftLog.Cypress/cypress/e2e/settings.cy.js
LiftLog.Ui/Pages/Feed/CreateFeedIdentityPage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/Settings/AppConfigPage.razor
LiftLog.Ui/Pages/Settings/BackupAndRestorePage.razor
LiftLog.Ui/Pages/Settings/ProgramListPage.razor
LiftLog.Ui/Pages/Settings/SettingsPage.razor
LiftLog.Ui/Shared/Presentation/LabelledFormRow.razor
LiftLog.Ui/Shared/Presentation/ListSwitch.razor
LiftLog.Ui/Shared/Presentation/ListTitle.razor
LiftLog.Ui/Shared/Presentation/ProgramListItem.razor
LiftLog.Ui/Shared/Presentation/ThemeChooser.razor
LiftLog.Ui/Shared/Smart/ProFeatures.razor

This replaces the existing card based settings with a list based one which is more in line with how material expects to be used.
Before:
After

Redesign settings to use a list based display 

---

LiftLog.Ui/Pages/Settings/NotificationsPage.razor
LiftLog.Ui/Pages/Settings/SettingsPage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/Smart/NavBar.razor
LiftLog.Ui/Store/App/AppActions.cs
LiftLog.Ui/Store/App/AppEffects.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionEffects.cs
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsFeature.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs

This setting allows users to disable the rest timer notifications

Add Rest Timer Notification Setting

---

LiftLog.App/App.xaml.cs
LiftLog.App/MainPage.xaml.cs
LiftLog.Ui/Store/App/AppActions.cs
LiftLog.Ui/Store/App/AppEffects.cs

When the app hasn't been opened for at least 30 minutes, and there is a completed session in the state, LiftLog will now automatically complete that session

Auto complete sessions

---

LiftLog.Ui/Models/CurrentSessionStateDao/CurrentSessionStateDaoV1.cs
LiftLog.Ui/Models/CurrentSessionStateDao/CurrentSessionStateDaoV2.cs
LiftLog.Ui/Pages/Feed/ViewFeedSessionPage.razor
LiftLog.Ui/Pages/History/HistoryEditPage.razor
LiftLog.Ui/Pages/SessionPage.razor
LiftLog.Ui/Shared/Presentation/TextField.razor
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/Store/CurrentSession/CurrentSessionActions.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionEffects.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionFeatures.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionState.cs
tests/LiftLog.Tests.App/Reducers/CurrentSessionReducerTests.cs

This simplifies usage, and consolidates the various ways of working with sessions

Convert the session component to a smart component

---

LiftLog.Api/Controllers/SharedItemController.cs
LiftLog.Api/Controllers/UserController.cs
LiftLog.Api/Controllers/UsersController.cs
LiftLog.Api/Db/UserDataContext.cs
LiftLog.Api/LiftLog.Api.csproj
LiftLog.Api/Migrations/UserData/20240704115106_RemoveSqids.Designer.cs
LiftLog.Api/Migrations/UserData/20240704115106_RemoveSqids.cs
LiftLog.Api/Models/SharedItem.cs
LiftLog.Api/Models/User.cs
LiftLog.Api/Program.cs

Using incrementing IDs for our users / shared items exposed us to an attack where someone could reverse engineer the alphabet and iterate the users.  Less than ideal, even though all data is encrypted, it would allow someone to send follow requests to all users

Migrate from sqids to cuids

---

LiftLog.App/LiftLog.App.csproj
LiftLog.App/MauiProgram.cs
LiftLog.App/Services/AppRatingEffects.cs
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Shared/Presentation/AppButton.razor
LiftLog.Ui/Shared/Smart/AppReviewRequest.razor
LiftLog.Ui/Store/App/AppActions.cs
LiftLog.Ui/Store/App/AppEffects.cs
LiftLog.Ui/Store/App/AppFeature.cs
LiftLog.Ui/Store/App/AppReducers.cs
LiftLog.Ui/Store/App/AppState.cs
LiftLog.Ui/Store/App/AppStateInitMiddleware.cs
LiftLog.Ui/ThemedWebApplication.razor

When the app has been opened 5 times, LiftLog will request a review from the user

Add a mechanism for tracking opens and requesting review

---

LiftLog.Lib/Models/SessionModels.cs
tests/LiftLog.Tests.App/SessionBehaviors/SessionSuperset.cs

Fix issue where superset on first exercise caused a crash

---

LiftLog.Ui/Pages/Feed/FeedPage.razor
LiftLog.Ui/Pages/History/HistoryPage.razor
LiftLog.Ui/Pages/Settings/ManageWorkoutsPage.razor
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Shared/Presentation/EmptyInfo.razor
LiftLog.Ui/Shared/Presentation/IconButton.razor
LiftLog.Ui/Shared/Presentation/SearchInput.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/Store/Program/ProgramEffects.cs

This PR adds a search bar to the stats page.  This will filter the exercises as you type.  It does not override the top level filters (30 days, sessions).

Add ability to search statistics

---

LiftLog.Maui/LiftLog.Maui.csproj
LiftLog.Maui/Properties/launchSettings.json
LiftLog.Ui/Shared/Smart/AppReviewRequest.razor

iOS builds have been broken a while, just trying a few things which might fix them

Go back to targeting ios (not 18)

---

LiftLog.Ui/Pages/Settings/SettingsPage.razor

This setting contains links to submitting a bug report/feature request in github. Additionally a button which links to the main github page.

Add support section to settings

---

LiftLog.Ui/i18n/UiStrings.de.resx

This PR adds German as a supported language! A massive thank you to @jasonhaak and @bschwehn for their efforts.

Add german (DE) translation!

---

LiftLog.Maui/Platforms/iOS/Info.plist
LiftLog.Ui/i18n/UiStrings.sr.resx

This PR integrates the Serbian language (in the latin alphabet) via the work of @aceydot
Thank you for all your work!

🇷🇸 Add Serbian 🇷🇸 translation

---

LiftLog.Maui/Platforms/iOS/Info.plist
LiftLog.Ui/i18n/UiStrings.fr.resx
README.md

This PR incorporates a translation into French, provided by @Kiddy-E
Thank you for your work!

Add 🇫🇷 French 🇫🇷 translation

---

LiftLog.Maui/Platforms/iOS/Info.plist
LiftLog.Ui/i18n/UiStrings.nl.resx
README.md

Thanks to the terrific efforts of @Jmulder99 LiftLog is now available in Dutch!
Fixes #397

🇳🇱 Add Dutch translation 🇳🇱

---

LiftLog.Maui/Platforms/iOS/Info.plist
LiftLog.Ui/i18n/UiStrings.fi.resx
README.md

Thanks to the efforts of @StarryLifeRedoArtisan LiftLog is now available in Finnish!
Fixes: #407

🇫🇮 Add Finnish Translation 🇫🇮

---

LiftLog.Ui/Shared/Presentation/TextField.razor

Dismiss the exercise searcher on enter

---

LiftLog.Ui/Pages/Settings/ProgramListPage.razor
LiftLog.Ui/i18n/UiStrings.resx

This commit just converts the New Plan and Plan page title to UiStrings

Add i18n for new plans

---

LiftLog.Lib/Models/SessionModels.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV1.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV2.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV2.proto
LiftLog.Ui/Services/PlaintextExportService.cs
LiftLog.Ui/Shared/Presentation/RestTimer.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/Shared/Smart/Tips/DifferentWeightDropsetTip.razor
LiftLog.Ui/Shared/Smart/Tips/HoldingRepCounterTip.razor
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs
LiftLog.Ui/Store/Stats/StatsEffects.cs
tests/LiftLog.Tests.App/Sessions.cs

Fixed all midnight glitches

---

LiftLog.Ui/Pages/Settings/AppConfigPage.razor
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/Presentation/FirstDayOfTheWeekSelector.razor
LiftLog.Ui/Shared/Presentation/HistoryCalendar.razor
LiftLog.Ui/Shared/Presentation/Select.razor
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs
LiftLog.Ui/i18n/UiStrings.resx

Add first day of the week setting and selector component

---

LiftLog.Ui/Shared/Presentation/PreviousExerciseViewer.razor

Fixes: #431 
https://github.com/user-attachments/assets/c42a6c4f-e279-46a3-ad57-d7e76377d27e

Add scroll to previous exercise viewer

---

LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs

Recently we moved to storing set times with dates. This means that changing the date in history did not update the stats or exports.
I have amended this code so that it will update the date of each set that is completed, while keeping it relative to the session's date.
This means that sessions which cross over midnight keep their set times consistent.
Fixes: #461

fix: Ensure changing a session date changes the set dates

---

LiftLog.Ui/i18n/UiStrings.nl.resx

Fixes some various typo across the file. 
Some inconsistencies like backup/back-up, goals/doelen.
Some small sentence structure/wording tweaks.

Updated the dutch language file to fix some typo's and inconsistencies

---

LiftLog.Ui/i18n/UiStrings.sr.resx

Update UiStrings.sr.resx so it's up to date.

Update Serbian latin translation

---

app/components/presentation/ms-icon-source.tsx
app/components/smart/copy-workout-dialog.tsx
app/components/smart/manage-workout-card-content.tsx
app/components/smart/shared-item.tsx
app/i18n/en.json

This commit adds a mechanism to copy workouts from one plan to another
https://github.com/user-attachments/assets/304cdb79-99bc-4e3a-af7f-70fb5b299c18

feat: Add ability to copy workouts between plans

---

app/app/(tabs)/history/edit.tsx
app/components/presentation/ms-icon-source.tsx
app/components/presentation/session-summary.tsx
app/components/smart/shared-item.tsx
app/services/feed-api.ts
app/store/feed/following-effects.ts
examples/remote-backup/reference-server-implementation/aws-lambda-s3-deployable/src/src/index.ts

This commit adds the share page for when a user has shared a plan with another user

Implement the share page
