LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Lib/Models/SessionModels.cs
LiftLog.Tests/Blueprints.cs
LiftLog.Tests/GlobalUsings.cs
LiftLog.Tests/LiftLog.Tests.csproj
LiftLog.Tests/Serialization/SerializationTests.cs
LiftLog.Tests/Sessions.cs
LiftLog.Ui/AssemblyInfo.cs
LiftLog.Ui/Models/ExerciseStatistics.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV1.cs
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Shared/Presentation/RestTimer.razor
LiftLog.Ui/Shared/Presentation/RestTimer.razor.cs
LiftLog.Ui/Shared/Presentation/StatGraphCardContent.razor
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs
LiftLog.Web/Services/WebNotificationService.cs

Since sessions have dates (which are editable), and recorded exercises also had dates, it was possible to have exercises be recorded on a different date to the session, which meant that stats wouldn't update when you change the date of a session

Update Recorded Exercise Completion times to be TimeOnly

---

LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Lib/Models/SessionModels.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV1.cs
LiftLog.Ui/Pages/History/HistoryEditPage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/SessionPage.razor
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Services/SessionService.cs
LiftLog.Ui/Shared/Presentation/SessionComponent.razor
LiftLog.Ui/Shared/Presentation/WeightDisplay.razor
LiftLog.Ui/Shared/Presentation/WeightFormat.razor
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Store/CurrentSession/CurrentSessionActions.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs

This allows a user to add their bodyweight at the end of a session.  The weight carries over from previous sessions for ease of use, and is also allowed to be unset

Add a bodyweight card to the end of sessions

---

LiftLog.Ui/Shared/Presentation/PotentialSetCounter.razor

We use a box shadow to do some sweet sweet animating between rep count colours,
however when combined with border radius you can see a small amount of the background peek through on the corners.
Super minor, but this commit just makes it so that the background matches the box shadow colour when the box shadow is present.
Adding a transition on the background colour is necessary because we need it to still be there for the entire lengtth of the box shadow animation. Hacky but works
Before:
After:

Fix visual artifacting

---

LiftLog.Ui/Shared/Presentation/PotentialSetCounter.razor

It was behaving annoyingly sometimes where the page would scroll unexpectedly when you finished a set.
Lets make it so it only scrolls it into view on the initial render

Only scroll repcount into view on first render

---

LiftLog.Ui/Shared/Presentation/RestTimer.razor
LiftLog.Ui/Shared/Presentation/SessionComponent.razor
LiftLog.Ui/Shared/Presentation/SnackBar.razor
LiftLog.Ui/Shared/Presentation/WeightToObjectComparison.razor

This PR adds a list of objects ranging from elephants to sunflower seeds, which the app will pick a random one from at the end of each session.  It then shows the user how many of that object's this session  was

Show the user an object from this world to compare how much they lifted to

---

LiftLog.Cypress/cypress/e2e/completing-a-session.cy.js
LiftLog.Cypress/cypress/e2e/creating-a-plan.cy.js
LiftLog.Cypress/cypress/e2e/settings.cy.js
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/Settings/SettingsPage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/Smart/Tips/DisablingTipsTip.razor
LiftLog.Ui/Shared/Smart/Tips/GeneralButtonInfoTip.razor
LiftLog.Ui/Shared/Smart/Tips/HoldingRepCounterTip.razor
LiftLog.Ui/Shared/Smart/Tips/NotesButtonTip.razor
LiftLog.Ui/Shared/Smart/Tips/PreviousButtonTip.razor
LiftLog.Ui/Shared/Smart/Tips/RestoringASessionTip.razor
LiftLog.Ui/Shared/Smart/Tips/Tips.razor
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsFeature.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs
LiftLog.Ui/_Imports.razor

There's a bit of hidden complexity and power that can be missed if you don't about it.
This PR just adds tips that will get shown to users.  When the tips have been cleared, they stay away until more tips are added, or the user resets them

Show tips to help users find their way around the app

---

LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs

The path to edit the exercise weight via the edit exercise modal meant that potential sets would not get updated

Ensure that set weights get updated when updating exercise

---

LiftLog.Cypress/cypress/e2e/completing-a-session.cy.js
LiftLog.Cypress/cypress/e2e/creating-a-plan.cy.js
LiftLog.Ui/Pages/Settings/ManageSessionPage.razor
LiftLog.Ui/Shared/CustomEvents.cs
LiftLog.Ui/Shared/Presentation/EditableIncrementer.razor
LiftLog.Ui/Shared/Presentation/ExerciseBlueprintSummary.razor
LiftLog.Ui/Shared/Presentation/ExerciseEditor.razor
LiftLog.Ui/Shared/Presentation/FixedIncrementer.razor
LiftLog.Ui/Shared/Presentation/FullScreenDialog.razor
LiftLog.Ui/Shared/Presentation/RestEditorGroup.razor
LiftLog.Ui/Shared/Presentation/RestFormat.razor
LiftLog.Ui/Shared/Presentation/RestTimer.razor
LiftLog.Ui/Shared/Presentation/StatGraphCardContent.razor
LiftLog.Ui/Shared/Presentation/Switch.razor
LiftLog.Ui/Store/Stats/StatsEffects.cs
LiftLog.Ui/Styles/app.css
LiftLog.Ui/index.js
LiftLog.Web/Services/WebThemeProvider.cs

The new design uses cards to group content, and cleans up rests dramatically.
<details>
<summary>Old Design</summary>
</details>
<details>
<summary>New Design</summary>
</details>

Restyle the exercise editor

---

LiftLog.Api/Service/GptAiWorkoutPlanner.cs

Open AI changed their pricing model, which means I had to prepurchase credits, which unlocked gpt-4.  It should still be cheap enough for me to run and might produce better results 🎉 
I'd like to look into locally hosting a model but not right now

Switch to gpt-4 for ai generation

---

Docs/FeedProcess.md
LiftLog.Api/Controllers/UserController.cs
LiftLog.Api/Controllers/UsersController.cs
LiftLog.Api/Migrations/UserData/20240407022930_StorePublicKeys.Designer.cs
LiftLog.Api/Migrations/UserData/20240407022930_StorePublicKeys.cs
LiftLog.Api/Models/User.cs
LiftLog.Lib/Models/UserActions.cs
LiftLog.Ui/Models/FeedStateDao.cs
LiftLog.Ui/Models/FeedStateDao.proto
LiftLog.Ui/Pages/Feed/FeedSharePage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Services/FeedIdentityService.cs
LiftLog.Ui/Shared/Smart/FeedShareUrl.razor
LiftLog.Ui/Store/Feed/FeedActions.cs
LiftLog.Ui/Store/Feed/FeedEffects.Following.cs
LiftLog.Ui/Store/Feed/FeedEffects.Identity.cs
LiftLog.Ui/Store/Feed/FeedFeature.cs
LiftLog.Ui/Store/Feed/FeedState.cs

Public keys are generally considered safe to share and store.  Originally we tried to go with a zero knowledge of any encryption keys by having the share URL include the RSA public key as part of the query params.  This allowed LiftLog to not store any keys on the server, even if they were used just to send inbox messages (Read: follow requests, and negotiating AES encryption) to users.
This was flawed for a couple reasons:
1. Liftlog still ran the CDNs, so a share url could very easily end up leaking a user's public key to LiftLog anyway
2. It made the share urls just unweildy and massive.  Users would be scared to click or share such a URL.
This PR amends the server to allow for storing RSA public keys against a user, and they will be returned when fetching that user.  With this …

Update feed share process to omit public key and store them on the backend

---

.vscode/settings.json
Docs/FeedProcess.md
LiftLog.Api/Controllers/UserController.cs
LiftLog.Api/Controllers/UsersController.cs
LiftLog.Api/Db/UserDataContext.cs
LiftLog.Api/LiftLog.Api.csproj
LiftLog.Api/Migrations/UserData/20240407111718_AddUserIndex.Designer.cs
LiftLog.Api/Migrations/UserData/20240407111718_AddUserIndex.cs
LiftLog.Api/Migrations/UserData/20240407113536_AddUserLookup.Designer.cs
LiftLog.Api/Migrations/UserData/20240407113536_AddUserLookup.cs
LiftLog.Api/Migrations/UserData/UserDataContextModelSnapshot.cs
LiftLog.Api/Models/User.cs
LiftLog.Api/Program.cs
LiftLog.Api/Service/IdEncodingService.cs
LiftLog.Lib/Models/UserActions.cs
LiftLog.Ui/Models/FeedStateDao.cs
LiftLog.Ui/Models/FeedStateDao.proto
LiftLog.Ui/Pages/Feed/FeedPage.razor
LiftLog.Ui/Pages/Feed/FeedSharePage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Services/FeedApiService.cs
LiftLog.Ui/Services/FeedIdentityService.cs
LiftLog.Ui/Services/UrlSafeConverter.cs
LiftLog.Ui/Shared/Smart/FeedShareUrl.razor
LiftLog.Ui/Store/Feed/FeedActions.cs
LiftLog.Ui/Store/Feed/FeedEffects.Following.cs
LiftLog.Ui/Store/Feed/FeedEffects.Identity.cs
LiftLog.Ui/Store/Feed/FeedState.cs

The share URLs are a bit big, even after doing the work to remove the public key from them.  This PR addresses this by adding a new field to the User model, `Lookup`.  At the database level, this is an auto incrementing integer.  However over the API we use the SqIds encoded form of the int, which gives a nice six(ish) character string representing that number, without exposing an API which would allow someone to easily enumerate over the users.
A new share url looks like:
https://app.liftlog.online/feed/share?id=JuG2jd&name=Lime
Which is super nice, and less overwhelming to recipients of share urls.
Old share urls will continue to work with this change.

Add a lookup field to users for shorter share urls

---

LiftLog.App/Platforms/Android/MainActivity.cs
LiftLog.Ui/Pages/Settings/SettingsPage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsFeature.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs

resolves: #156 
This PR adds a new toggle in the settings "Status Bar fix" which when enabled, forces the top of the app to be offset by a static amount (46 px, which seems close to the offset from a hole punchout on a pixel 4a).
Ideally this setting can be removed, but I cannot seem to reproduce the issue on an emulator or my real devices...

Add workaround for status bar covering buttons

---

LiftLog.App/LiftLog.App.csproj

Secure storage backups in android end up creating issues when a user reinstalls from a backup.
Following recommendations found here: https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/secure-storage?view=net-maui-8.0&tabs=android We can disable backup for secure storage prefs, while keeping app data
resolves: #155

Allow backup, except secure storage

---

LiftLog.Ui/Shared/Smart/NavBar.razor
LiftLog.Ui/Store/App/AppActions.cs
LiftLog.Ui/Store/App/AppFeature.cs
LiftLog.Ui/Store/App/AppReducers.cs
LiftLog.Ui/Store/App/AppState.cs

This means that when a user navigates away from a page which is within the settings tree, if they navigate to the settings with nav, it will take them right back to that page, rather than the root of settings.
Clicking settings again will bring them to the root
https://github.com/LiamMorrow/LiftLog/assets/13741016/0ce5f94a-465a-43f9-830e-75507f7d54c1

Amend nav search behaviour to remember last settings page

---

LiftLog.Ui/Shared/Presentation/PotentialSetAdditionalActions.razor

On IOS when the user long pressed a set, and didn't hold long enough it would register a click for where their finger was, which was sometimes over one of the rep count selections in the dialog.  This would cause unintended rep selections.
The fix here is to just move those additional actions from onclick to onpointerdown

Fix long press potential set

---

LiftLog.Ui/Shared/Presentation/StatGraphCardContent.razor
LiftLog.Ui/wwwroot/app-utils.js

Capture the width of the card, then set the width of the stats so that they take up the entire width.
This fixes an issue where stats on large screens only take up the first 300ish px.
Weirdly, setting width to 100% does not fix it :(
Before 
After

Ensure stat graphs take up entire width

---

LiftLog.Api/Controllers/UserController.cs
LiftLog.Api/Validators/UserRequestValidators.cs
LiftLog.Lib/Models/UserActions.cs
LiftLog.Ui/Pages/Feed/CreateFeedIdentityPage.razor
LiftLog.Ui/Pages/Feed/FeedPage.razor
LiftLog.Ui/Services/FeedIdentityService.cs
LiftLog.Ui/Store/Feed/FeedActions.cs
LiftLog.Ui/Store/Feed/FeedStateInitMiddleware.cs

These accounts will be configured to not publish anything, however features with sharing are about to be built which will require feed features.

Automatically create feed accounts on app startup

---

LiftLog.App/Platforms/Android/MainActivity.cs
LiftLog.App/Platforms/Android/WebViewSoftInputPatch.cs

The android keyboard would cover inputs when it shows up.  This PR uses a modified fix from https://github.com/dotnet/maui/issues/14197#issuecomment-1535561632
to ensure that the viewport shrinks when the keyboard is shown.
It also amends the initial safe insets to take into account the status bar and navigation bar.  This might fix https://github.com/LiamMorrow/LiftLog/issues/156
Before:
https://github.com/LiamMorrow/LiftLog/assets/13741016/637ea2e5-61a6-4729-9244-bf1e2f5da42e
After:
https://github.com/LiamMorrow/LiftLog/assets/13741016/c7c0a358-0a2d-4da4-b2a4-615aaf465702

Fix issue where android keyboard covers input

---

LiftLog.Ui/Shared/Presentation/EditableIncrementer.razor
LiftLog.Ui/Shared/Presentation/TextField.razor
LiftLog.Ui/wwwroot/app-utils.js

On android, when the keyboard was dismissed, it would reset the value of the textfield
This commit changes the behaviour of the textfields to emit their values on input rather than onchange, which ensures the state is always up to date.
This was an issue before because on inputs which used decimals, it would strip the decimal point during the state loop, meaning the user couldn't input them.  I fixed this by only updating the internal input's value from the props when it doesn't have focus
Before:
https://github.com/LiamMorrow/LiftLog/assets/13741016/db9587b2-a727-4037-9782-096780530ac6
After:
https://github.com/LiamMorrow/LiftLog/assets/13741016/8fd9dfae-26ad-4ef1-aba0-523def9ef79c

Fix issue dismissing keyboard resetting value

---

LiftLog.Api/Controllers/SharedItemController.cs
LiftLog.Api/Validators/SharedItemRequestValidators.cs
LiftLog.Lib/Models/ShareActions.cs
LiftLog.Ui/LiftLog.Ui.csproj
LiftLog.Ui/Models/FeedStateDao.cs
LiftLog.Ui/Models/FeedStateDao.proto
LiftLog.Ui/Models/SharedItem.cs
LiftLog.Ui/Models/SharedItem.proto
LiftLog.Ui/Pages/Feed/FeedPage.razor
LiftLog.Ui/Pages/Feed/FeedSharedItemPage.razor
LiftLog.Ui/Pages/Settings/ProgramListPage.razor
LiftLog.Ui/Services/FeedApiService.cs
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Shared/Presentation/ProgramListItem.razor
LiftLog.Ui/Shared/Smart/FeedShareUrl.razor
LiftLog.Ui/Shared/Smart/SharedItemComponent.razor
LiftLog.Ui/Shared/Smart/SharedProgramBlueprintComponent.razor
LiftLog.Ui/Store/Feed/FeedActions.cs
LiftLog.Ui/Store/Feed/FeedFeature.cs
LiftLog.Ui/Store/Feed/FeedReducers.cs
LiftLog.Ui/Store/Feed/FeedSharingEffects.cs
LiftLog.Ui/Store/Feed/FeedState.cs
LiftLog.Ui/Store/RemoteData.cs
LiftLog.Ui/_Imports.razor
LiftLog.Ui/wwwroot/app-utils.js
LiftLog.Web/Properties/launchSettings.json
tests/LiftLog.Tests.Api/Integration/SharedItemIntegrationTests.cs

A user of the app is now able to share their plans.  This will use the API created in #185 to publish an encrypted plan.  The encryption AES key and the ID returned from the API is used to create a URL which can be shared with other liftlog users. Similarly to how the feed sharing used to work, the AES key is not stored anywhere, and never touches the liftlog API servers.  
An example of a (non working) url:
```
https://app.liftlog.online/feed/shared-item/Xu5mjK?k=A9D914F00210B7BCB11E9E9F015CD933
```
On loading of that url, the app pulls the shared item with the given ID, then decrypts it with the key.  RSA validation is also done via the user who shared the item's public key (also returned in the api response).
In doing this, I've introduced a RemoteData type, which can be used to …

Implement sharing plans

---

LiftLog.Cypress/cypress/e2e/completing-a-session.cy.js
LiftLog.Lib/Models/SessionModels.cs
LiftLog.Ui/Pages/History/HistoryPage.razor
LiftLog.Ui/Shared/Presentation/Card.razor
LiftLog.Ui/Shared/Presentation/CardList.razor
LiftLog.Ui/Shared/Presentation/HistoryCalendar.razor
LiftLog.Ui/Shared/Presentation/HistoryCalendarDay.razor
LiftLog.Ui/Shared/Presentation/SessionSummary.razor
LiftLog.Ui/Store/App/AppActions.cs
LiftLog.Ui/Store/App/AppFeature.cs
LiftLog.Ui/Store/App/AppReducers.cs
LiftLog.Ui/Store/App/AppState.cs
LiftLog.Ui/Store/Stats/StatsEffects.cs
LiftLog.Ui/wwwroot/twconf.json

This PR achieves three things:
1.  Show the per set weight in stats (as the max of all set weights) and history (as individual chips)
2. Wrap the sets and weight in session summary (shown in feed, history, and the upcoming workouts) in nice little chip things
3. Brings back cards on this history page... I still feel like we should move away from them but I can't make it look good - better be consistent
Before (no chips):
After:
Fixes: #236

Show per set weights as chip like things in summaries / stats

---

LiftLog.Lib/Models/SessionModels.cs
LiftLog.Maui/LiftLog.Maui.csproj
LiftLog.Ui/Store/CurrentSession/CurrentSessionState.cs
tests/LiftLog.Tests.App/Encryption/OsEncryptionServiceTests.cs
tests/LiftLog.Tests.App/GlobalUsings.cs
tests/LiftLog.Tests.App/LiftLog.Tests.App.csproj
tests/LiftLog.Tests.App/SessionBehaviors/SessionSuperset.cs
tests/LiftLog.Tests.App/Sessions.cs

Fixes #246
This PR fixes a behaviour where a chain of 3 (or more) exercises in superset would not cycle properly. Instead of cycling through each of the exercises in order, it would get to the end of the chain then cycle between the last two exercises.

Allow for supersets to behave in chains of more than 2

---

.github/workflows/format.yml
LiftLog.Lib/Models/SessionModels.cs
renovate.json

Renovate often updates csharpier, causing new formatting requirements which manually need to be approved.  Since we will always accept these, let's have the check format command actually apply formatting and commit it whenever we're in a renovate PR

Format and commit code when renovate updates

---

LiftLog.Api/LiftLog.Api.csproj
LiftLog.Api/Service/PurchaseVerificationService.cs
LiftLog.Lib/Services/IEncryptionService.cs
LiftLog.Lib/Services/OsEncryptionService.cs
LiftLog.Maui/LiftLog.Maui.csproj
LiftLog.Maui/Services/AppHapticFeedbackService.cs
LiftLog.Maui/Services/AppThemeProvider.cs
LiftLog.Ui/LiftLog.Ui.csproj
LiftLog.Ui/Models/FeedStateDao.cs
LiftLog.Ui/Models/UserEvent.proto
LiftLog.Ui/Services/FeedFollowService.cs
LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/Store/CurrentSession/CurrentSessionEffects.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs
LiftLog.Ui/Store/Feed/FeedEffects.Following.cs
LiftLog.Web/LiftLog.Web.csproj
LiftLog.Web/Services/JsEncryptionService.cs
LiftLog.Web/Services/WebThemeProvider.cs
LiftLog.Web/wwwroot/crypto-utils.ts

Basically it was possible to forge an inbox message (such as unfollow a user) by:
`MaliciousUser`
1. Creating an InboxMessage saying to `Unfollow[SubjectUserId=UserA]`
2. Signing/encrypting that message with `VictimUser`'s RSA key
3. Sending the encrypted message to `VictimUser`
When `VictimUser` receives the message, they see a message which is  sent by `MaliciousUser`, however the only verification is that the message is for `VictimUser` - which it is.  This used to be slightly less of an issue when PublicKeys used to encrypt inbox messages were secret, however they are entirely public now.
This PR remedies this by adding an additional `Signature` field to `InboxMessages` which is:
```
[InnerMessagePayloadBytes,ToUserId,SubjectUserId]
```
Signed with the private key of the …

Add RSA verification that inbox message came from the user who it relates to

---

LiftLog.Lib/Models/SessionModels.cs
tests/LiftLog.Tests.App/SessionBehaviors/SessionSuperset.cs

In a session with the second to last exercise marked as superset (so that is supersets with the last exercise), it was not possible to complete the session.
Additional fix for #246

Fix: finish session when last exercise is superset

---

.github/workflows/backupserver-build.yml
.github/workflows/backupserver-publish.yml
.gitignore
Docs/RemoteBackup.md
LiftLog.BackupServer/LiftLog.BackupServer.csproj
LiftLog.BackupServer/Program.cs
LiftLog.BackupServer/Properties/launchSettings.json
LiftLog.BackupServer/README.md
LiftLog.BackupServer/appsettings.json
LiftLog.Ui/LiftLog.Ui.csproj
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/Settings/BackupAndRestore/RemoteBackupPage.razor
LiftLog.Ui/Pages/Settings/BackupAndRestorePage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsFeature.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs
LiftLog.sln
release_notes/whatsnew-en-AU

This PR solves https://github.com/LiamMorrow/LiftLog/issues/243
It does this by adding a mechanism whereby the LiftLog app can `POST` a raw backup file to an arbitrary web URL whenever it has unbacked up changes.  
As part of this, a simple API project has been added which implements the backup server by persisting these backups to timestamped files on disk. 
Backup process:
```
Whenever the user opens the main page (Upcoming workouts)
If there has been changes since the last backup was sent - POST a backup to the specified endpoint
```
It's specified in the documentation, but I'll note it again here.  This feature requires that the endpoint is HTTPS due to restrictions in mobile environments.

Add a mechanism for Automatic Remote Backups

---

LiftLog.Ui/Shared/Presentation/ItemTitle.razor

Fixes an issue where the item titles in stats would overflow their parent container
Fixes: #249
Before:
After:

Ensure that item titles do not overflow

---

LiftLog.Ui/Pages/History/HistoryPage.razor
LiftLog.Ui/Shared/Presentation/Card.razor
LiftLog.Ui/Shared/Presentation/CardList.razor
LiftLog.Ui/Shared/Presentation/ConfirmationDialog.razor
LiftLog.Ui/Shared/Presentation/Dialog.razor
LiftLog.Ui/Shared/Presentation/VirtualizedCardList.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/Shared/Smart/Tips/HoldingRepCounterTip.razor
LiftLog.Ui/wwwroot/app-utils.js

I was lazily using the oncontextmenu event to do long press, however this does not fire on iOS.
This commit switches to using a custom long press based on timers and pointer events (similar to what we do elsewhere).
As part of this I noticed that the dialog will be cancelled immediately on long press in iOS due to it firing some pointer events when the user hasn't moved enough.  To fix this, I just disabled scrim cancellation in those dialogs which are triggered by long press.
Fixes #263

Fix iOS long press not firing

---

LiftLog.Lib/Util/EnumerableExtensions.cs
LiftLog.Ui/Pages/SessionPage.razor
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Shared/Presentation/ExerciseSummary.razor
LiftLog.Ui/Shared/Presentation/IconButton.razor
LiftLog.Ui/Shared/Presentation/ItemList.razor
LiftLog.Ui/Shared/Presentation/PreviousExerciseViewer.razor
LiftLog.Ui/Shared/Presentation/SessionSummary.razor
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Shared/Smart/Tips/PreviousButtonTip.razor

This PR replaces the "Hold to view previous" in a weighted exercise with a "Tap to view history" action.  Instead of showing a graph over time and replacing the current values, it just shows a list of historical completions of that exercise- with weight and how many reps in each set as chips.
Before:
https://github.com/user-attachments/assets/c87b06fa-5256-4bfd-9355-bf1d8ca84b30
After:
https://github.com/user-attachments/assets/57b2d2fa-9364-4ac8-a6b0-97f8e21fd42a

Replace previous hold graph with list

---

LiftLog.Maui/Platforms/Android/Resources/xml/network_security_config.xml
LiftLog.Ui/Store/Settings/SettingsEffects.cs

One of the requirements for auto backup is the server uses HTTPS.  We need the app to allow self signed certs for use cases where users have used self signed certs.
See: https://github.com/LiamMorrow/LiftLog/issues/243#issuecomment-2366866412

Add trust anchors for user certificates

---

LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Ui/Store/Stats/StatsEffects.cs

This PR relaxes the restriction of having to have the exact same name/reps/sets to show up in the exercise history list.

Include exercises with different reps in previous history

---

LiftLog.Api/Service/GptAiWorkoutPlanner.cs
LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Ui/Models/SessionBlueprintDao/SessionBlueprintDaoV1.cs
LiftLog.Ui/Models/SessionBlueprintDao/SessionBlueprintDaoV2.cs
LiftLog.Ui/Models/SessionBlueprintDao/SessionBlueprintDaoV2.proto
LiftLog.Ui/Pages/Screenshot/ScreenshotCollectorPage.Home.cs
LiftLog.Ui/Pages/Settings/ManageSessionPage.razor
LiftLog.Ui/Services/BuiltInProgramService.cs
LiftLog.Ui/Shared/Presentation/ExerciseEditor.razor
LiftLog.Ui/Shared/Presentation/TextField.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/wwwroot/app-utils.ts
tests/LiftLog.Tests.App/Blueprints.cs

This link will automatically fill if the clipboard contains a link when you paste into any of the name, notes, or link fields.
Right now it is not displayed anywhere and is ornamental, but as specified in #281 I'd like to add an "info" icon which can extend exercise names, perhaps put the notes in there, and hold this link.  This link can be used for anything, but its purpose is to link to "How to do" exercises, say if you are copying a plan from somewhere into liftlog.

Add link field to exercises

---

LiftLog.Maui/App.xaml.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV1.cs
LiftLog.Ui/Services/ProgressRepository.cs
LiftLog.Ui/Shared/Presentation/StatGraphCardContent.razor
LiftLog.Ui/Store/Feed/FeedEffects.FeedItems.cs
LiftLog.Ui/Store/Stats/StatsEffects.cs

This PR Fixes: #283 
All dates/times in LiftLog are stored in Local time (no offset or timezone information).
This PR acheives two things:
1. Ensure that we specify the `Kind` whenever we create a DateTime from a DateOnly/TimeOnly as Local.  This has no effect on the issue addressed in this PR but it is good to be explicit.
2. Amends the apex charts options to specify that our dates are not UTC, so it should display them verbatim
Additionally, this PR amends the stats calculations to show sessions in the bodyweight card even when there are no exercises in that session

Ensure datetimes are always local + displayed as local in charts

---

LiftLog.Ui/Shared/Presentation/HistoryCalendar.razor

The calendar was incorrectly showing the previous month's days in reverse order as shown in this screenshot:
This PR fixes it so that they are displayed in correct ascending order

Fix calendar showing previous month days backwards

---

LiftLog.Cypress/cypress/e2e/completing-a-session.cy.js
LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Ui/Services/ProgressRepository.cs
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Store/Stats/StatsEffects.cs

https://github.com/LiamMorrow/LiftLog/pull/280 introduced an issue where the next time you do an exercise with the same name, it set the weight to the previous weight (with progressive overload), regardless of if it was the same amount of reps/sets.
This PR fixes that behaviour so weight only carries over if the reps and sets are the same as well as the exercise name (original behaviour).

Ensure weight of next exercise comes from same number of reps

---

LiftLog.Ui/Shared/Presentation/WeightedExercise.razor

This commit fixes the issue where the next set was not showing a focus ring.  In the migraiton away from 'hold previous to show it', a bad path was followed which always set the next set to be -1.
Before:
After

Fix: Rep counter not showing focus ring

---

LiftLog.Lib/Util/EnumerableExtensions.cs
LiftLog.Ui/Services/ProgressRepository.cs

We attempted to do this in #280 but we only got half way there. 
Before:
After:

Show exercises which fuzzy match in previous list

---

LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Shared/Presentation/CardList.razor

The default behaviour was to reuse the same component as the list changes, however we should not be reusing the stats cards as they do not rerender on changes. Fixes: #295

Specify a key when rendering the list of stats

---

LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor

Fixes: #292 
A previous commit accidentally exposed the previous button on the history page, this PR just hides it again

Hide the previous button on the history and feed page

---

LiftLog.Ui/Pages/Feed/FeedPage.razor
LiftLog.Ui/Pages/Feed/ViewFeedSessionPage.razor
LiftLog.Ui/Pages/History/HistoryEditPage.razor
LiftLog.Ui/Pages/History/HistoryPage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/PostSessionPage.razor
LiftLog.Ui/Pages/SessionPage.razor
LiftLog.Ui/Shared/Smart/NavBar.razor
LiftLog.Ui/Store/App/AppActions.cs
LiftLog.Ui/Store/App/AppFeature.cs
LiftLog.Ui/Store/App/AppReducers.cs
LiftLog.Ui/Store/App/AppState.cs

The 'current session' has a behaviour where navigating with the nav bar remembers it and keeps it open, without having to go back to the 'base' page first.
This commit adds this behaviour for history and feed.  The advantage of this is now you can open a historical session, go back to your current session, and go back to the historical session, without having to find it in the list again.
Simply tap the nav button again to go to the 'base' page.
Before:
https://github.com/user-attachments/assets/ee0c78bb-3075-46b9-83a0-e64932f4d0b1
After:
https://github.com/user-attachments/assets/c634e85b-4ea7-431d-b0c9-afd9750139f1

Remember and reopen history and feed pages when navigating

---

LiftLog.Lib/Models/SessionModels.cs
LiftLog.Ui/Services/SessionService.cs

Sometimes a user does a freeform session during their plan.  This no longer resets their progress through their plan
Fixes: #293 
https://github.com/user-attachments/assets/d219b282-a153-484b-a786-a555c10ddf2d

Stop freeform exercises from interrupting plan

---

LiftLog.Ui/Shared/Presentation/ExerciseSummary.razor

If all completed sets have the same reps, show the actual number of reps like "3x4@10kg" rather than the target number of reps.

Fix: Previous sessions show correct number of reps

---

.github/workflows/ios-build.yml
.github/workflows/ios-publish.yml
LiftLog.Ui/Pages/Settings/BackupAndRestore/PlainTextExportPage.razor
LiftLog.Ui/Pages/Settings/BackupAndRestorePage.razor
LiftLog.Ui/Shared/Smart/Tips/PlainTextExportTip.razor
LiftLog.Ui/Shared/Smart/Tips/Tips.razor
release_notes/whatsnew-en-AU

Just adds a tip to let people know that plaintext export is available

Add a tip on plaintext

---

LiftLog.Api/Db/UserDataContext.cs
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/Settings/BackupAndRestorePage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Shared/Smart/BackupAlert.razor
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsFeature.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs

As liftlog stores all data locally on device, it is important that backups are created regularly.
Users which don't use the automatic backup feature are prone to data loss if their phone breaks.
This PR adds a new alert which fires every 7 days, which will suggest a backup

Add a backup reminder

---

LiftLog.Ui/Shared/Presentation/PotentialSetAdditionalActions.razor

**Problem:** When trying to scroll down in the scrollfield on exercises with a high rep count (30+ for example) the rep count button where you try to scroll on gets selected because it used `onpointerdown`. This makes it difficult on mobile to scroll down to select higher rep counts, since you have to scroll on a small area besides the buttons and the border. See video:
https://github.com/user-attachments/assets/e4d6eeda-4f1d-455a-945f-28c4620dd391
**Solution:** Use `onclick` event instead on rep count button. This way the rep button will only be selected when actually clicked not just when the pointer is down over the element.
**NOTE:** I have only tested this in the web version (not android or ios). The reason being that i couldn't get the project to build. Every time I tried, it said …

Scrolling on selecting rep count

---

LiftLog.Ui/Shared/Presentation/ExerciseEditor.razor
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor

This commit adds a button to the overflow menu on the weighted exercise, which allows a user to open a link that they have put against their exercise
fixes: #324

Add a menu button to open links

---

LiftLog.Ui/Pages/Feed/FeedPage.razor
LiftLog.Ui/Pages/Feed/FeedUserPlanPage.razor
LiftLog.Ui/Pages/Feed/ViewFeedSessionPage.razor
LiftLog.Ui/Pages/History/HistoryEditPage.razor
LiftLog.Ui/Pages/Settings/AiPlannerPage.razor
LiftLog.Ui/Pages/Settings/AiSessionCreatorPage.razor
LiftLog.Ui/Pages/Settings/AppConfigPage.razor
LiftLog.Ui/Pages/Settings/BackupAndRestore/PlainTextExportPage.razor
LiftLog.Ui/Pages/Settings/BackupAndRestore/RemoteBackupPage.razor
LiftLog.Ui/Pages/Settings/BackupAndRestorePage.razor
LiftLog.Ui/Pages/Settings/ManageSessionPage.razor
LiftLog.Ui/Pages/Settings/ManageWorkoutsPage.razor
LiftLog.Ui/Pages/Settings/NotificationsPage.razor
LiftLog.Ui/Pages/Settings/SettingsPage.razor
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Shared/Smart/AppReviewRequest.razor
LiftLog.Ui/Shared/Smart/BackupAlert.razor
LiftLog.Ui/Shared/Smart/NavBar.razor

It is recommended that we call the base at the start, in case we accidentally don't call it in a branch, or we cause a navigate, disposing the component
See: https://liftlog.sentry.io/issues/6040370251/?project=4505937523769344&query=&statsPeriod=14d&stream_index=24

Move all base.OnInitialized calls to start

---

LiftLog.Maui/Platforms/iOS/AppDelegate.cs
LiftLog.Maui/Platforms/iOS/Program.cs

This commit amends the IOS app to introspect the decimal separator from the native IOS locale settings, and updates the culture to match.
The existing behaviour seems to be to use the language code only to set the decimal formatter, however ios allows users to configure number formatting independently of language/region.
Fixes #332
https://github.com/user-attachments/assets/cc9f9ab8-1b80-4570-9f33-d7642631e89d

Fix decimal separator

---

LiftLog.Ui/Pages/Feed/FeedUserPlanPage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Pages/Settings/AiPlannerPage.razor
LiftLog.Ui/Pages/Settings/AiSessionCreatorPage.razor
LiftLog.Ui/Shared/MainLayout.razor
LiftLog.Ui/Shared/Presentation/AppButton.razor
LiftLog.Ui/Shared/Presentation/Select.razor
LiftLog.Ui/Shared/Presentation/WeightDialog.razor
LiftLog.Ui/Shared/Smart/ProFeatures.razor
LiftLog.Ui/Shared/Smart/SessionComponent.razor

In order to ensure that we can use the same strings for titles and other buttons with different capitalization requirements, we simply apply this with css.
AppButtons
They require that ONLY the first letter is capitalized
Title
The title should be in title case (more or less, words like And get capitalized)

Use CSS for capitalization of AppButton and title

---

LiftLog.Ui/i18n/UiStrings.de.resx

This just fixes a minor typo I did not notice before.
Sorry for making you apply the other changes manually rather than simply creating an MR in the first place.

Fix minor typo in German Translation

---

LiftLog.Cypress/cypress/e2e/completing-a-session.cy.js
LiftLog.Cypress/cypress/e2e/settings.cy.js
LiftLog.Cypress/cypress/support/commands.js
LiftLog.Lib/Models/BlueprintModels.cs
LiftLog.Lib/Models/SessionModels.cs
LiftLog.Ui/Models/CurrentSessionStateDao/CurrentSessionStateDaoV1.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV1.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV2.cs
LiftLog.Ui/Models/SessionHistoryDao/SessionHistoryDaoV2.proto
LiftLog.Ui/Pages/Settings/AppConfigPage.razor
LiftLog.Ui/Pages/StatsPage.razor
LiftLog.Ui/Repository/PreferencesRepository.cs
LiftLog.Ui/Services/SessionService.cs
LiftLog.Ui/Shared/Presentation/ExerciseSummary.razor
LiftLog.Ui/Shared/Presentation/ListSwitch.razor
LiftLog.Ui/Shared/Presentation/WeightedExercise.razor
LiftLog.Ui/Store/AiSessionCreator/AiSessionCreatorEffects.cs
LiftLog.Ui/Store/CurrentSession/CurrentSessionReducers.cs
LiftLog.Ui/Store/Settings/SettingsActions.cs
LiftLog.Ui/Store/Settings/SettingsEffects.cs
LiftLog.Ui/Store/Settings/SettingsReducers.cs
LiftLog.Ui/Store/Settings/SettingsState.cs
LiftLog.Ui/Store/Settings/SettingsStateInitMiddleware.cs
LiftLog.Ui/Store/Stats/StatsEffects.cs
LiftLog.Ui/Store/Stats/StatsState.cs
LiftLog.Ui/i18n/UiStrings.resx
tests/LiftLog.Tests.App/Reducers/CurrentSessionReducerTests.cs
tests/LiftLog.Tests.App/Serialization/SerializationTests.cs
tests/LiftLog.Tests.App/Sessions.cs

Splitting each set into having its own weight has always kept this idea of "main" weight, which is the top level weight.  Progressive overload was driven by this main weight, and the next time a user completed an exercise, LiftLog would ignore the "per set" weight choices from the previous session.  This PR does two things:
1. When specifying per set weight, there is no longer a "main" weight
2. The next time you start an exercise, each set inherits the weight of the previous session's set (plus progressive overload)
This essentially removes the idea of a "main" weight, and in most places just replaces it with any of the set's weights (we use max).
Note that there is no "main" weight on squats since it is split by set

Overhaul per set weight

---

LiftLog.Ui/Shared/Presentation/HistoryCalendar.razor

resolves #379
Tested by manually setting firstDayOfWeek and dayOfFirstDayOfTheWeek variables to both Monday and Saturday, assuming this will change automatically due to DefaultThreadCurrentCulture but was unable to find a way to test that myself.

First day of week support

---

.github/workflows/ui-test.yml
LiftLog.Cypress/cypress.config.js
LiftLog.Ui/Pages/Feed/FeedUserPlanPage.razor
LiftLog.Ui/Pages/History/HistoryPage.razor
LiftLog.Ui/Pages/Index.razor
LiftLog.Ui/Shared/Presentation/ExerciseSummary.razor
LiftLog.Ui/Shared/Presentation/ExerciseSummary.razor.cs
LiftLog.Ui/Shared/Presentation/FeedItemCardContent.razor
LiftLog.Ui/Shared/Presentation/ManageWorkoutCardContent.razor
LiftLog.Ui/Shared/Presentation/PreviousExerciseViewer.razor
LiftLog.Ui/Shared/Presentation/SessionSummary.razor
LiftLog.Ui/Shared/Smart/SharedProgramBlueprintComponent.razor
LiftLog.Web/Properties/AssemblyInfo.cs
LiftLog.Web/Properties/launchSettings.json

A regression caused the history / previously done exercise chips to show the same amount of reps and weight, no matter how much was actually lifted. This PR fixes this behaviour, and displays the chips in a scrolling panel rather than stacked.
Fixes: #404 #408
For a workout completed as such:
Previously:
Now:

fix: Previously lifted exercise chips split

---

LiftLog.Ui/Pages/StatsPage.razor

For some reason NRE is not working on this razor page - so the possible null pointer was not caught at compile time.
Fixes: #445

fix: NPE in session select on stats page

---

LiftLog.Ui/Shared/Smart/SessionComponent.razor
LiftLog.Ui/i18n/UiStrings.resx

- Added a confirmation dialog for the "Finish" button in the workout session flow.
- The dialog appears when the session target is WorkoutSession, allowing users to confirm before ending workout.
- If not a workout session, SaveSession is called directly without confirmation.
- **Language support**: The confirmation dialog text has been added to the resource file in English, but language translations are not yet included.
- **Testing**: The feature has not been fully tested yet, though it has been implemented with the same logic in other Razor pages.
Add confirmation to “Finish” button #439

Add confirmation dialog before finishing workout session

---

LiftLog.Ui/i18n/UiStrings.es.resx

While using the app, I noticed that the wrong time is shown for the max rest time in Spanish

Fix RestBetween string showing wrong rest times with Spanish localization

---

app/assets/math-plus-minus.svg
app/babel.config.js
app/components/presentation/editable-incrementer.tsx
app/components/presentation/exercise-editor.tsx
app/components/presentation/ms-icon-source.tsx
app/components/presentation/weight-dialog.tsx
app/hooks/useAppTheme.tsx
app/i18n/en.json
app/package-lock.json
app/package.json
app/types/svg.d.ts
tests/cypress-tests/cypress/e2e/completing-a-session.cy.js

The iOS keyboard does not allow for BOTH negative and decimal numbers. Who would need that right?
Fixes: #527 
Anyway this commit adds a +- button next to any weight inputs

feat: Add ability to set negative numbers
